### PR TITLE
Manual panning

### LINKED ISSUE #33: Manual panning
Autopanning is kind of slow; maybe people should be able to take over?

### PR DESCRIPTION
**Pull request by SheepTester**
The camera still automatically pans; however, you can scroll/drag to pan manually. Doing so will pause automatic panning for five seconds.

It also can detect clicking vs dragging (this can be seen in cocnept-designs/sean/students-roam.html)

Resolves #33

### CODE REVIEW

**Comment by briarsychung** [comment]
Bro why do you like autopan so much
PS. How are you writing code so damn fast??

**Comment by SheepTester** [comment]
There's no other indication that the camera is cropped

**Comment by briarsychung** [comment]
Idk or you could add it to the intro 
Orr could have a setting for autopan like a little checkbox, it's just that I tend to find it super annoying

**Comment by SheepTester** [comment]
It won't autopan if you manually pan though lol

**Comment by briarsychung** [comment]
I mean I just don't see how autopan would be useful because indication that the camera is cropped doesn't need to be persistent

**Comment by SheepTester** [comment]
oof

**Comment by briarsychung** [comment]
I'm fine with autopan; I just think it would be nice to be able to turn it off

**Comment by SheepTester** [comment]
ok

**Comment by SheepTester** [comment]
It is off by default; hopefully that brings you pleasure

**Pull request merged**
