### PR TITLE
Show focus ring for people who use tab key

### LINKED ISSUE #40: Tab focus ring
Since we're doing the forbidden

```css
:focus {
    outline: none;
}
```

we should still show tab focus for those who prefer using the tab key. There's [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) but it's [a bit too new](https://caniuse.com/#search=focus-visible)

We could use the [polyfill](https://github.com/WICG/focus-visible) or use the [one I've been using](https://github.com/Orbiit/elimination/blob/master/js/tab-key-focus.js)

### PR DESCRIPTION
**Pull request by SheepTester**
image

Right now it's an unsightly bright red outline, which should help people know what is focused, though it also blends with red buttons.

Fixes #40

### CODE REVIEW

**Comment by briarsychung** [comment]
Maybe white would work better for all buttons? And maybe a tiny bit thinner.

**Comment by SheepTester** [comment]
Ok

**Comment by SheepTester** [comment]
image

@Nichodon thin and white, ~~the ideal body type~~

**Comment by briarsychung** [comment]
<comment></comment>

**Pull request merged**
